### ISSUE TITLE
Buena refactorizacion

### ISSUE THREAD

**Issue by semurat** [fermarja/t5_tic_tac_toe#1]
Imagino que llegaste a este metodo tras una refactorizacion, bien visto y buen uso del colaborador, mockeado y simulando su comportamiento.

https://github.com/fermarja/t5_tic_tac_toe/blob/3bb76fefc7854258ae41f0a2b6316b6ee76a1dd8/src/test/java/es/jcyl/cag/cursotesting/tictactoe/TicTacToeTest.java#L195

**Comment by fermarja** [comment]
Si, en ab66c020270267febc0c2f2672fe55d305aecd96 lo extraje asi porque si entre tanto texto no se veian bien las posiciones que iba a jugar.

Gracias
